# Generated by Django 4.2 on 2025-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="translated_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
