# Generated by Django 4.2 on 2025-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="jsonfile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="jsonfile",
            table="json_files",
        ),
        migrations.AlterModelTable(
            name="message",
            table="messages",
        ),
    ]
